{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "update"
	},
	"OnFailure": "/DreamsBank/Actions/UpdateEntityFailureMessage.action",
	"OnSuccess": "/DreamsBank/Actions/UpdateEntitySuccessMessage.action",
	"Target": {
		"EntitySet": "Aspirante",
		"Service": "/DreamsBank/Services/dreamsbankkk.service",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"cedula": "#Control:cedula/#Value",
		"nombre": "#Control:nombre/#Value",
		"edad": "#Control:edad/#Value",
		"carrera": "#Control:carrera/#Value",
		"semestre": "#Control:semestre/#Value",
		"universidad": "#Control:universidad/#Value",
		"telefono": "#Control:telefono/#Value",
		"correo": "#Control:correo/#Value"
	}
}