{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/DreamsBank/Pages/KnowledgePeople/Datos_Maestros/Aspirante/Aspirante_Create.page",
    "_Type": "Action.Type.Navigation"
}