{
	"_Type": "Action.Type.OfflineOData.Upload",
	"ActionResult": {
		"_Name": "UploadOff"
	},
	"OnSuccess": "/DreamsBank/Actions/Service/DownloadOff.action",
	"Service": "/DreamsBank/Services/dreamsbankkk.service",
	"UploadCategories": [
		"Transacciones"
	]
}