{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "update"
	},
	"OnFailure": "/DreamsBank/Actions/UpdateEntityFailureMessage.action",
	"OnSuccess": "/DreamsBank/Actions/UpdateEntitySuccessMessage.action",
	"Target": {
		"EntitySet": "Productos",
		"Service": "/DreamsBank/Services/dreamsbankkk.service",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"nombre": "#Control:nombre/#Value",
		"descripcion": "#Control:descripcion/#Value",
		"valor": "#Control:valor/#Value"
	}
}