{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "NavTo_Estudiante_Create"
	},
	"PageToOpen": "/DreamsBank/Pages/KnowledgeRun/Estudiante/Estudiante_Create.page",
	"ModalPage": true,
	"ModalPageFullscreen": false
}